# Generated by Django 4.1.3 on 2022-11-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Number', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('Image', models.ImageField(upload_to='img')),
                ('Date', models.DateField(null=True)),
                ('Function', models.CharField(max_length=50)),
            ],
        ),
    ]
