# Generated by Django 4.1.3 on 2022-12-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
