# Generated by Django 4.1.3 on 2022-12-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0002_alter_user_db_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_db',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
