# Generated by Django 4.1.3 on 2022-12-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_user', '0003_alter_user_db_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_db',
            name='C_Accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='C_Reject',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='D_Accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='D_Reject',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='P_Accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='P_Reject',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='S_Accept',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='user_db',
            name='S_Reject',
            field=models.BooleanField(default='False'),
        ),
    ]
