# Generated by Django 4.1.3 on 2022-12-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
