# Generated by Django 4.1.3 on 2022-12-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0003_alter_product_desc_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor_db',
            name='Image',
            field=models.ImageField(default='media/default.jpg', upload_to='img'),
        ),
    ]
