# Generated by Django 4.1.3 on 2022-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0004_alter_decor_db_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor_db',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
