# Generated by Django 4.1.3 on 2022-12-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0005_alter_decor_db_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='DID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='even_decor.decor_db'),
        ),
    ]
