# Generated by Django 4.1.3 on 2022-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0006_category_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Book',
            field=models.BooleanField(default='False'),
        ),
    ]
