# Generated by Django 4.1.4 on 2023-01-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0009_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='book',
        ),
    ]
