# Generated by Django 4.1.4 on 2023-01-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0010_rename_booking_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Spotid',
            new_name='Decorid',
        ),
    ]
