# Generated by Django 4.1.4 on 2023-01-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0011_rename_spotid_book_decorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='drate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Number', models.CharField(max_length=50)),
                ('userid', models.CharField(default='0', max_length=20)),
                ('prodid', models.CharField(default='0', max_length=20)),
                ('Decorid', models.CharField(default='0', max_length=20)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
    ]
