# Generated by Django 4.1.4 on 2023-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0012_drate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
