# Generated by Django 4.1.4 on 2023-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0013_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
