# Generated by Django 4.1.4 on 2023-01-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0014_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
