# Generated by Django 4.1.4 on 2023-02-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0015_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paystatus',
            field=models.BooleanField(default='False'),
        ),
    ]
