# Generated by Django 4.1.4 on 2023-02-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('even_decor', '0018_rename_productid_d_image_did'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_image',
            old_name='DID',
            new_name='ProductID',
        ),
    ]
