# Generated by Django 4.1.4 on 2023-01-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
