# Generated by Django 4.1.4 on 2023-01-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_cater', '0005_c_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_product',
            name='FCategory',
        ),
        migrations.DeleteModel(
            name='F_Category',
        ),
    ]
