# Generated by Django 4.1.4 on 2023-01-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_cater', '0006_remove_f_product_fcategory_delete_f_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_book',
            old_name='Spotid',
            new_name='caterid',
        ),
    ]
