# Generated by Django 4.1.4 on 2023-01-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_cater', '0008_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_book',
            name='rate',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
