# Generated by Django 4.1.4 on 2023-02-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_cater', '0013_c_book_paystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='cater')),
                ('ProductID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='event_cater.f_product')),
            ],
        ),
    ]
