# Generated by Django 4.1.3 on 2022-12-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_category',
            name='PID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='event_photography.photo_db'),
        ),
    ]
