# Generated by Django 4.1.3 on 2022-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_photography', '0002_p_category_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_product',
            name='Book',
            field=models.BooleanField(default='False'),
        ),
    ]
