# Generated by Django 4.1.3 on 2022-12-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_photography', '0003_p_product_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_product',
            name='userid',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
