# Generated by Django 4.1.4 on 2023-01-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_photography', '0005_p_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p_book',
            old_name='Spotid',
            new_name='photoid',
        ),
    ]
