# Generated by Django 4.1.4 on 2023-01-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_photography', '0009_p_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_book',
            name='review',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
