# Generated by Django 4.1.3 on 2022-12-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Number', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Businessname', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=15)),
                ('Image', models.ImageField(upload_to='Spot')),
                ('Experience', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='S_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Desc', models.CharField(max_length=500)),
                ('Price', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='cater')),
                ('SpotID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='event_spot.spot_db')),
            ],
        ),
    ]
