# Generated by Django 4.1.3 on 2022-12-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_spot', '0004_s_product_accept_s_product_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_product',
            name='Accept',
        ),
        migrations.RemoveField(
            model_name='s_product',
            name='Reject',
        ),
    ]
