# Generated by Django 4.1.4 on 2023-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_spot', '0008_s_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_product',
            name='rate',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
